framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
        #################################################
        ### APRES AVOIR AJOUTER UN NOUVEAU TRANSPORT ####
        ############### STOPER LES WORKERS ##############
        ################ VIDER LE CACHE #################
        ############## RELANCER LES WORKERS #############

        routing:
            #Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            #App\Message\AccountCreatedNotification: async
            #App\Message\AdminNotification: async
            App\Message\EmailNotification: async
            #Symfony\Component\Notifier\Message\ChatMessage: async
            #Symfony\Component\Notifier\Message\SmsMessage: async

