twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    # ajout du service CatsAndSubCatsService pour injecter les categories et sous categories dans la variable globale: catsAndSubCats
    globals:
        catsAndSubCats: '@App\Service\CatsAndSubCatsService'
        brands: '@App\Service\BrandsService'

when@test:
    twig:
        strict_variables: true


