twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    # ajout du service CatsAndSubCatsService pour injecter les categories et sous categories dans la variable globale: catsAndSubCats
    globals:
        catsAndSubCats: '@App\Service\GlobalVarsService'
        allbrands: '@App\Service\GlobalVarsService'
        new_order_count: '@App\Service\GlobalVarsService'
    # ajout du style pour les emails - voir base_email.html.twig pour l'appel du style
    paths:
        '%kernel.project_dir%/public/assets/styles': styles_email
when@test:
    twig:
        strict_variables: true


