framework:
    workflows: 
        picture_publishing:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'state' #methode de mon entité Picture
            supports:
                - App\Entity\Picture
            initial_marking: new
            places:
                - new
                - process
                - done
            transitions:
                process:
                    from: new
                    to: process
                done:
                    from: process
                    to: done