name: Deploy on dist
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de la branche
        uses: actions/checkout@v3
        with:
           ref: ${{ github.event.pull_request.head.ref }}
      - name: Update main branch
        run: |
          git pull origin main
          git push
