name: Deploy on dist
on:
  pull_request:
    branches: [ main ]
    types : [ closed ]

jobs:
  merge_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Update main branch on server
        run: |
          git config pull.ff true
