name: Update main branch

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Update main branch
        run: |
          git config pull.ff true
          composer install --no-scripts --no-dev --no-interaction
          php bin/console doctrine:schema:update --force
          git push

