name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      ## ssh from github actions to ubuntu server
      - name: SSH into Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: /home/simon/.ssh/id_ed25519  # Utilisez la clé privée générée sur votre hôte local
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/html/StoreProject
            git stash
            git pull
            bin/console cache:clear
