name: Update main branch

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Update main branch
        run: |
          git pull origin main
          php /usr/bin/composer install --no-scripts --no-dev
          php /usr/bin/composer dump-autoload --optimize --no-dev --classmap-authoritative
          php bin/console doctrine:schema:update --force
          git push

