name: Update main branch

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Update main branch
        run: |
          git checkout main
          git pull
          composer install --no-interaction --no-suggest --no-progress --prefer-dist
          php bin/console doctrine:schema:update --force
          git push

